server:
  host: localhost
  port: 8080

# multipartFile 용량 늘려주는 설정
spring:
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: create-drop
      format_sql : true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/media?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jongha
    password: Whdgk13579!

#logging:
#  level:
#    org:
#      springframework: debug
#      web: debug
