server:
  port: 0

aws:
  secretsmanager:
    name: jikji
cloud:
  aws:
    s3:
      bucket: jongha
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false

# multipartFile 용량 늘려주는 설정
spring:
  application:
    name: media-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/media?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jongha
    password: Whdgk13579!

#logging:
#  level:
#    org:
#      springframework: debug
#      web: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka